---
- name: Deploy Lotod Docker Stack
  hosts: server
  become: true

  vars:
    deploy_dir: /opt/lotod

  tasks:
    - name: Ensure deployment directory exists
      file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose template
      template:
        src: docker-compose-lotod-stuff.yml.j2
        dest: "{{ deploy_dir }}/docker-compose.yml"
        mode: '0644'

    # Optional: Uncomment if nginx.conf is needed
    # - name: Copy nginx.conf
    #   copy:
    #     src: templates/nginx.conf
    #     dest: "{{ deploy_dir }}/nginx.conf"
    #     mode: '0644'

    # If using Docker Compose v1
    - name: Launch containers (v1)
      shell: docker-compose up -d
      args:
        chdir: "{{ deploy_dir }}"
      ignore_errors: yes  # Optional, in case this fails and you want to try v2 next

    # If using Docker Compose v2
    - name: Launch containers (v2)
      shell: docker compose up -d
      args:
        chdir: "{{ deploy_dir }}"
