---
- name: Deploy Lotod Docker Stack
  hosts: server  # your inventory group or host
  become: true

  vars:
    deploy_dir: /opt/lotod

  tasks:
    - name: Ensure deployment directory exists
      file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose template
      template:
        src: docker-compose.yml.j2   # changed from templates/docker-compose-lotod-stuff.yml.j2
        dest: "{{ deploy_dir }}/docker-compose.yml"
        mode: '0644'

    - name: Copy nginx.conf
      copy:
        src: nginx.conf   # assuming this file is also in the repo root or adjust path accordingly
        dest: "{{ deploy_dir }}/nginx.conf"
        mode: '0644'

    - name: Launch containers
      shell: docker-compose up -d
      args:
        chdir: "{{ deploy_dir }}"
