---
- name: Deploy Lotod Docker Stack
  hosts: server  # <-- changed from lotod_hosts to server
  become: true

  vars:
    deploy_dir: /opt/lotod

  tasks:
    - name: Ensure deployment directory exists
      file:
        path: "{{ deploy_dir }}"
        state: directory
        mode: '0755'

    - name: Copy docker-compose template
      template:
        src: templates/docker-compose-lotod-stuff.yml.j2
        dest: "{{ deploy_dir }}/docker-compose.yml"
        mode: '0644'

    - name: Copy nginx.conf
      copy:
        src: templates/nginx.conf
        dest: "{{ deploy_dir }}/nginx.conf"
        mode: '0644'

    - name: Launch containers
      shell: docker-compose up -d
      args:
        chdir: "{{ deploy_dir }}"
